# \[STBDA\] 11wk: MaxPool2D, Conv2D

김보람  
2023-07-13

> 해당 강의노트는 전북대학교 최규빈교수님
> [STBDA2022](https://guebin.github.io/STBDA2022/) 자료임

### imports

In [2]:
import tensorflow as tf
import tensorflow.experimental.numpy as tnp
import numpy as np
import matplotlib.pyplot as plt

In [3]:
tnp.experimental_enable_numpy_behavior()

In [4]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

In [5]:
X = tf.constant(x_train.reshape(-1,28,28,1),dtype=tf.float64)
y = tf.keras.utils.to_categorical(y_train)
XX = tf.constant(x_test.reshape(-1,28,28,1),dtype=tf.float64)
yy = tf.keras.utils.to_categorical(y_test)

`-` 첫시도

In [6]:
net1 = tf.keras.Sequential()
net1.add(tf.keras.layers.Flatten())
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(10,activation='softmax'))
net1.compile(optimizer='adam', loss=tf.losses.categorical_crossentropy,metrics='accuracy')
net1.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 1.0329 - accuracy: 0.7892
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4472 - accuracy: 0.8415
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4179 - accuracy: 0.8497
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3942 - accuracy: 0.8598
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3756 - accuracy: 0.8668

In [7]:
net1.evaluate(XX,yy)

313/313 [==============================] - 0s 754us/step - loss: 0.4255 - accuracy: 0.8505

In [8]:
net1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 500)               392500    
                                                                 
 dense_1 (Dense)             (None, 500)               250500    
                                                                 
 dense_2 (Dense)             (None, 500)               250500    
                                                                 
 dense_3 (Dense)             (None, 500)               250500    
                                                                 
 dense_4 (Dense)             (None, 10)                5010      
                                                                 
Total params: 1,149,010
Trainable params: 1,149,010
Non-

`-` 두번째 시도

In [9]:
net2 = tf.keras.Sequential()
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D())
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D())
net2.add(tf.keras.layers.Flatten())
#net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(10,activation='softmax'))
net2.compile(optimizer='adam', loss=tf.losses.categorical_crossentropy,metrics='accuracy')
net2.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.7960 - accuracy: 0.8061
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3814 - accuracy: 0.8644
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3400 - accuracy: 0.8769
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3182 - accuracy: 0.8854
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3011 - accuracy: 0.8914

In [10]:
net2.evaluate(XX,yy)

313/313 [==============================] - 0s 815us/step - loss: 0.3572 - accuracy: 0.8707

In [11]:
net2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 27, 27, 30)        150       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 30)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 12, 12, 30)        3630      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 30)         0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 1080)              0         
                                                                 
 dense_5 (Dense)             (None, 10)               

In [12]:
14590/ 1149010

In [14]:
c1, m1, c2, m2, flttn, dns = net2.layers

In [15]:
print(X.shape) # 입력이미지 = 2D
print(c1(X).shape) #2D
print(m1(c1(X)).shape)  #2D
print(c2(m1(c1(X))).shape) #2D
print(m2(c2(m1(c1(X)))).shape) #2D
print(flttn(m2(c2(m1(c1(X))))).shape)# 1D
print(dns(flttn(m2(c2(m1(c1(X)))))).shape)# 1D

(60000, 28, 28, 1)
(60000, 27, 27, 30)
(60000, 13, 13, 30)
(60000, 12, 12, 30)
(60000, 6, 6, 30)
(60000, 1080)
(60000, 10)

### MaxPool2D

#### 테스트1

`-` 레이어생성

In [16]:
m=tf.keras.layers.MaxPool2D()

`-` 입력데이터

In [17]:
XXX = tnp.arange(1*4*4*1).reshape(1,4,4,1)
XXX.reshape(1,4,4)

> <span style="color:blue"> 흑백 이미지다 생각하고 뒤에 채널 생략하자 걍
> 보기쉽게

`-` 입력데이터가 레이어를 통과한 모습

In [18]:
m(XXX).reshape(1,2,2)

`-` MaxPool2D layer의 역할: (2,2)윈도우를 만들고 (2,2)윈도우에서 max를
뽑아 값을 기록, 윈도우를 움직이면서 반복

#### 테스트2

In [20]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

In [21]:
m(XXX).reshape(1,3,3)

#### 테스트3

In [22]:
m=tf.keras.layers.MaxPool2D(pool_size=(3, 3))

In [23]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

In [24]:
m(XXX).reshape(1,2,2)

#### 테스트4

In [25]:
m=tf.keras.layers.MaxPool2D(pool_size=(2, 2))

In [26]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

In [27]:
m(XXX).reshape(1,2,2)

In [28]:
m=tf.keras.layers.MaxPool2D(pool_size=(2, 2),padding="same")

In [29]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

In [30]:
m(XXX).reshape(1,3,3)

#### 테스트5

In [31]:
XXX = tnp.arange(2*4*4*1).reshape(2,4,4,1)
XXX.reshape(2,4,4)

In [32]:
m(XXX).reshape(2,2,2)

#### 테스트6

In [33]:
XXX = tnp.arange(1*4*4*3).reshape(1,4,4,3)

In [34]:
XXX[...,0]

In [35]:
m(XXX)[...,0]

### Conv2D

#### 테스트1

`-` 레이어생성

In [36]:
cnv = tf.keras.layers.Conv2D(1,(2,2))

`-` XXX생성

In [37]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)
XXX.reshape(1,4,4)

> <span style="color:blue"> dytpe이 int형이면 에러가 나므로 float형으로
> 바꿔주기

In [38]:
cnv(XXX).reshape(1,3,3)

-   XXX에서 cnv(XXX)로 가는 맵핑을 찾는건 쉽지 않아보인다.
-   심지어 랜덤으로 결정되는 부분도 있어보임 $\to$
    <span style="color:blue"> 계속 값이 바뀜

`-` 코드정리 + 시드통일

In [56]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(2,2))
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)

`-` conv의 입출력

In [57]:
print(XXX.reshape(1,4,4))
print(cnv(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ -5.372491  -6.5789    -7.785309]
  [-10.198126 -11.404535 -12.610944]
  [-15.023762 -16.230171 -17.436579]]], shape=(1, 3, 3), dtype=float32)

`-` conv연산 추론

In [42]:
type(cnv.weights)

In [58]:
tf.reshape(cnv.weights[0],(2,2))

In [59]:
0 * -0.2408014 + 1 * 0.3118649 + 4 * -0.70300657 + 5 * -0.5744659 + 0

`-` 내가 정의한 weights를 대입하여 conv 연산 확인

In [61]:
cnv.get_weights()[0].shape

In [62]:
w = np.array([1/4,1/4,1/4,1/4],dtype=np.float32).reshape(2, 2, 1, 1)
b = np.array([3],dtype=np.float32)

In [63]:
cnv.set_weights([w,b])

In [64]:
XXX.reshape(1,4,4)

In [65]:
cnv(XXX).reshape(1,3,3)

In [66]:
np.mean([0,1,4,5])+3, np.mean([1,2,5,6])+3, np.mean([2,3,6,7])+3

#### tf.keras.layers.Conv2D(1,kernel_size=(2,2)) 요약

`-` 요약

1.  size=(2,2)인 윈도우를 만듬.

2.  XXX에 윈도우를 통과시켜서 (2,2)크기의 sub XXX 를 얻음. sub XXX의 각
    원소에 conv2d.weights\[0\]의 각 원소를 element-wise하게 곱한다.

3.  (2)의 결과를 모두 더한다. 그리고 그 결과에 다시
    conv2d.weights\[1\]을 수행

4.  윈도우를 이동시키면서 반복!

#### 테스트2

`-` 레이어와 XXX생성

In [70]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(3,3))
XXX = tnp.arange(1*5*5*1,dtype=tf.float64).reshape(1,5,5,1)

In [71]:
XXX.reshape(1,5,5) ## 입력: XXX

In [74]:
cnv(XXX).reshape(1,3,3) ## 출력: conv(XXX)

In [76]:
tf.reshape(cnv.weights[0],(1,3,3)) ## 커널의 가중치

In [77]:
tf.reduce_sum(XXX.reshape(1,5,5)[0,:3,:3] * tf.reshape(cnv.weights[0],(3,3)))

#### 테스트3

![](https://github.com/guebin/2021BDA/blob/master/_notebooks/2021-11-04-conv.png?raw=true)

In [78]:
XXX = tf.constant([[3,3,2,1,0],[0,0,1,3,1],[3,1,2,2,3],[2,0,0,2,2],[2,0,0,0,1]],dtype=tf.float64).reshape(1,5,5,1)
XXX.reshape(1,5,5)

In [79]:
cnv = tf.keras.layers.Conv2D(1,(3,3))

In [80]:
cnv.weights

> <span style="color:blue"> 처음엔 weights가 없다가

In [81]:
cnv(XXX).reshape(1,3,3)

In [82]:
cnv.weights[0]

> <span style="color:blue"> XXX가 cnv를 통과하면서 weights가 생긴다.

In [86]:
_w = tf.constant([[0,1,2],[2,2,0],[0,1,2]],dtype=tf.float64).reshape(3,3,1,1)
_b = tf.constant([0],dtype=tf.float64)

In [87]:
cnv.set_weights([_w,_b])

In [88]:
cnv(XXX).reshape(1,3,3)

#### 테스트4

In [89]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(2,2))
XXX = tnp.arange(2*5*5*1,dtype=tf.float64).reshape(2,5,5,1)

In [90]:
print(XXX.reshape(2,5,5))
cnv(XXX) # weights를 초기화 시키기 위해서 레이어를 1회 통과
cnv.set_weights([w,b])
print(cnv(XXX).reshape(2,4,4))

tf.Tensor(
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]], shape=(2, 5, 5), dtype=float64)
tf.Tensor(
[[[ 6.  7.  8.  9.]
  [11. 12. 13. 14.]
  [16. 17. 18. 19.]
  [21. 22. 23. 24.]]

 [[31. 32. 33. 34.]
  [36. 37. 38. 39.]
  [41. 42. 43. 44.]
  [46. 47. 48. 49.]]], shape=(2, 4, 4), dtype=float32)

In [91]:
np.mean([0,1,5,6])+3,np.mean([25,26,30,31])+3,

#### 테스트5

`-`

In [92]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2),activation='relu')
XXX = tnp.arange(1*2*2*1,dtype=tf.float64).reshape(1,2,2,1)

In [93]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[0. 1.]
  [2. 3.]]], shape=(1, 2, 2), dtype=float64)

In [94]:
cnv(XXX)

In [95]:
cnv.weights[0] # (2,2) 커널의 크기 // 1은 XXX의 채널수 // 4는 conv(XXX)의 채널수

In [ ]:
cnv.weights[0][...,0].reshape(2,2) ## conv(XXX)의 첫번째채널 출력을 얻기 위해 곱해지는 w

In [ ]:
tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2)) ### conv(XXX)의 첫번째 채널 출력결과

`-` 계산결과를 확인하기 쉽게 하기 위한 약간의 트릭

In [ ]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2))
XXX = tnp.array([1]*1*2*2*1,dtype=tf.float64).reshape(1,2,2,1)

In [ ]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[1. 1.]
  [1. 1.]]], shape=(1, 2, 2), dtype=float64)

-   이렇게 XXX를 설정하면 cnv(XXX)의 결과는 단지 cnv의 weight들의 sum이
    된다.

In [ ]:
cnv(XXX)

In [ ]:
cnv.weights[0] # (2,2) 커널의 크기 // 1은 XXX의 채널수 // 4는 conv(XXX)의 채널수

In [ ]:
cnv.weights[0][...,0].reshape(2,2) ## conv(XXX)의 첫번째채널 출력을 얻기 위해 곱해지는 w

In [ ]:
tf.reduce_sum(cnv.weights[0][...,0])
#tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2)) ### conv(XXX)의 첫번째 채널 출력결과

#### 테스트6

`-` 결과확인을 쉽게하기 위해서 XXX를 1로 통일

In [ ]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2))
XXX = tnp.array([1]*1*2*2*3,dtype=tf.float64).reshape(1,2,2,3)

In [ ]:
cnv(XXX)

In [ ]:
cnv.weights[0] ## (2,2)는 커널의 사이즈 // 3은 XXX의채널 // 4는 cnv(XXX)의 채널

In [ ]:
cnv.weights[0][...,0] ## cnv(XXX)의 첫번째 채널결과를 얻기 위해서 사용하는 w

In [ ]:
tf.reduce_sum(cnv.weights[0][...,0]) ### cnv(XXX)의 첫번째 채널의 결과

In [ ]:
print(tf.reduce_sum(cnv.weights[0][...,0]))
print(tf.reduce_sum(cnv.weights[0][...,1]))
print(tf.reduce_sum(cnv.weights[0][...,2]))
print(tf.reduce_sum(cnv.weights[0][...,3])) ### cnv(XXX)의 결과

tf.Tensor(0.32976213, shape=(), dtype=float32)
tf.Tensor(-0.44983464, shape=(), dtype=float32)
tf.Tensor(-1.0487392, shape=(), dtype=float32)
tf.Tensor(-1.5800952, shape=(), dtype=float32)

In [ ]:
w_red = cnv.weights[0][...,0][...,0]
w_green = cnv.weights[0][...,0][...,1]
w_blue = cnv.weights[0][...,0][...,2]

In [ ]:
tf.reduce_sum(XXX[...,0] * w_red + XXX[...,1] * w_green + XXX[...,2] * w_blue) ## cnv(XXX)의 첫채널 출력결과

### hw

아래와 같은 흑백이미지가 있다고 하자.

    0 0 0 1 1 1
    0 0 0 1 1 1
    0 0 0 1 1 1
    0 0 0 1 1 1
    0 0 0 1 1 1
    0 0 0 1 1 1

위의 이미지에 아래와 같은 weight를 가진 필터를 적용하여 convolution한
결과를 계산하라. (bias는 0으로 가정한다)

    -1 1
    -1 1