# 리스트

## 선언

`-` 리스트의 선언

In [2]:
a=[11,22]
a

[11, 22]

In [3]:
type(a)

list

`-` 비어있는 리스트의 선언

In [4]:
a=[] # 방법1
a

[]

In [5]:
a=list() # 방법2
a

[]

## 연산

`-` 더하기연산

In [6]:
a=[11,22]
b=[12,13]

In [7]:
a

[11, 22]

In [8]:
b

[12, 13]

In [9]:
a+b

[11, 22, 12, 13]

- 우리의 예상과 다른 결과가 나옴 $\to$ 파이썬은 R처럼 자체적으로 좋은 계산기능을 내장하고 있찌 않음

`-` 브로드캐스팅과 같이 R에서는 당연히 가능했던 기능을 사용할 수 없음

In [12]:
a=[1,2,3]
b=1
a+b

TypeError: can only concatenate list (not "int") to list

`-` 뺄셈은 정의되지 않음

In [13]:
a=[1,2]
b=[1,2]
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기는 정의 가능



In [14]:
a=[1,2]

In [15]:
2*a  #a+a

[1, 2, 1, 2]

`-` 나눗셈은 정의되지 않음

In [16]:
a=[1,2,1,2]
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기는 원소의 추가와 반복추가를 의미하지만 그렇다고 해서 뺄샘과 나눗셈이 원소의 삭제를 의미하는 것은 아님

In [18]:
a=[1,2,3]
a-[3]   #이런건없다

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [19]:
a=[1,2,1,2,1,2,]
a/3    # 이런건없다

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기가 원소의 추가와 반복추가를 의미하여 편리할때도 있긴하지만, 우리는 산술적인 `+`, `*`를 원하는 경우도 있다. 
이럴 경우는 어떻게 할 수 있을까?

(예제)

In [25]:
a=[1,2]
b=[3,4]

a+b=[4,6]이 되도록 하려면?

(풀이1)

In [22]:
type(a)

list

In [23]:
type(a[0])

int

In [26]:
a[0]+b[0]  #a의 첫번째 원소 추출, b의 첫번째 원소 추출, 둘을 더함

4

In [27]:
a[1]+b[1]

6

In [28]:
[a[0]+b[0], a[1]+b[1]]

[4, 6]

풀이가 가능한 이유? a,b는 리스트이지만 a[0], a[1], b[0], b[1]은 각각 인트형임. 인트형은 +연산이 가능함

(풀이2)

numpy패키지 (파이썬의 여러 수치연산들을 담당하는 라이브러리)
- 이러한 벡터연산은 누구나 필요로 하는 연산
- 내가 아니더라도 누군가가 프로그램화 해놓았을 것임
- 그 누군가가 자신이 만든 코드를 잘 정리하여 무료로 배포했을 수도 있음 (패키지를 배포한다고 표현)
- 그 패키지를 가져와서 설치한 뒤 사용하기만 하면 된다.

패키지를 설치하는 방법
- `!pip install numpy`  # 최신버전을 설치함
- `!conda install -c conda-forge numpy -y`  # 안전한 버전을 설치함

설치된 패키지를 사용하는 방법
- `import numpy` 한뒤에 `numpy.??`로 기능을 사용
- `import numpy as np` 한뒤에 `np.??`로 기능을 사용

파이썬의 기본 패키지
numpy pandas matplotlib

In [44]:
!pip install numpy

In [29]:
import numpy # 설치한 패키지를 쓰겠다고 선언함 library(tidyverse)와 비슷.

In [30]:
a=[1,2]
b=[3,4]

In [31]:
a+b

[1, 2, 3, 4]

In [33]:
type(numpy.array(a))

numpy.ndarray

In [36]:
aa=numpy.array(a)   #aa는 리스트가 아니라 넘파이 어레이, numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미
bb=numpy.array(b)   

In [37]:
aa+bb

array([4, 6])

In [38]:
a+b

[1, 2, 3, 4]

이런것도 가능

In [39]:
2*aa+1

array([3, 5])

In [40]:
2*aa+1+bb

array([6, 9])

(풀이3)

In [41]:
import numpy as np # 설치한 numpy라는 패키지를 쓰겠음. 그런데 numpy 말고 np라는 이름으로 쓰겠음

In [42]:
np.array(a)+np.array(b)

array([4, 6])

## 인덱싱

`-` str형과 동일한 방식

In [45]:
a=[11,22,33,44,55]

In [46]:
a[0:3]

[11, 22, 33]

# 리스트 고급

## 콘테이너형 객체, 가변객체

`-` 객체 - Object - Something 

`-` 리스트의 원소는 int, float따위만 가능한 것이 아니다. (리스트는 콘테이너형 객체이므로)

In [47]:
lst = [1,3.14,True, 'a', [1,2],
      (1,2), {'name':'iu','age':30},{1,2,3}]

In [48]:
lst

[1, 3.14, True, 'a', [1, 2], (1, 2), {'name': 'iu', 'age': 30}, {1, 2, 3}]

각 원소의 타입을 알아보자

In [49]:
type(lst[0])

int

In [50]:
type(lst[1])

float

In [51]:
type(lst[2])

bool

In [52]:
type(lst[3])

str

In [53]:
type(lst[4])

list

In [54]:
type(lst[5])

tuple

In [55]:
type(lst[6])   # dictionary

dict

In [56]:
type(lst[7]) #집합

set

`-` str은 컨테이너형이 아니다

In [57]:
# 컨테이너형이 아닌것
'abcd'[0]

'a'

- str의 모든 원소는 문자임

`-` 리스트의 원소를 수정할 수 있다. (리스트는 가변객체이므로)

In [60]:
a=[11,22,33]

In [61]:
a[0]

11

In [62]:
a[0]=111

In [63]:
a

[111, 22, 33]

`-` 원소수정은 당연한 기능 같은데 이것이 불가능한 경우도 있다.

(가능한경우)

In [64]:
'boram'[1]

'o'

In [65]:
a=['b','o','r','a','m']

In [66]:
a[0]

'b'

In [67]:
a[0]='B'

In [68]:
a

['B', 'o', 'r', 'a', 'm']

(불가능한경우)

In [69]:
a='boram'

In [70]:
a

'boram'

In [71]:
a[0]

'b'

In [72]:
a[0]='B'

TypeError: 'str' object does not support item assignment

`-` 리스트 원소 삭제

(예제)

아래와 같이 문자로 된 리스트를 선언하자.

In [74]:
a=['b','o','r','a','m']
a

['b', 'o', 'r', 'a', 'm']

사실 더 쉽게 선언할 수 있음

In [82]:
a='boram'   #string으로 a를 선언

In [83]:
type(a)

str

In [84]:
list(a)

['b', 'o', 'r', 'a', 'm']

In [85]:
a=list(a)  #list(a)를 통하여 str을 list로 변환 

In [86]:
a  # 그 결과를 a에 다시 저장

['b', 'o', 'r', 'a', 'm']

첫 번째 원소를 삭제하고 싶다면?

In [87]:

del a[0]
a

['o', 'r', 'a', 'm']

`-` 리스트의 원소 추가

(예제) 비어있는 리스틀를 만들고 원소 0,1,2 를 차례로 추가하여 보자.

(풀이1)

In [96]:
a=[]
a

[]

In [97]:
a= a+[0]
a

[0]

In [98]:
a=a+[1]
a

[0, 1]

In [99]:
a= a+[2]
a

[0, 1, 2]

(풀이2)

In [101]:
a=[]
a

[]

In [102]:
a+=[0]
a

[0]

In [103]:
a+=[1]
a

[0, 1]

In [104]:
a+=[2]
a

[0, 1, 2]

- 암기법: 중복되는 변수를 지우고 연산자의 순서를 바꾼다.

(풀이3) 리스트 특화기능(=메소드)를 이용

In [105]:
a=[]
a

[]

In [106]:
a.append?

In [107]:
a.append(0)
a

[0]

In [108]:
a.append(1)
a

[0, 1]

In [109]:
a.append(2)
a

[0, 1, 2]

`-` `a+[4]`와 `a.append(4)`의 차이점은?

(관찰1)

In [111]:
a=[1,2,3]
a+[4]  ## 리스트 a와 리스트 [4]의 연산결과

[1, 2, 3, 4]

In [112]:
a  # a는 그대로임. 변화없음

[1, 2, 3]

(관찰2)

In [113]:
a=[1,2,3]
a.append(4)

In [114]:
a    # a자체가 변화함

[1, 2, 3, 4]

비슷해보이지만 굉장히 미묘한 차이가 있음

`a.append(4)` : `a`에 4를 append하라 $\to$ `a`가 변함
    
`a+[4]` : `a`와 4를 연산하고 수행결과를 보여달라

## 메소드(리스트자료형에 특화된 특수한 함수들)

**(append)**

In [119]:
a=[1,2,3,4]
a.append?

In [120]:
a.append(5)
a

[1, 2, 3, 4, 5]

**(clear)**

In [121]:
a=[1,2,3,4]
a.clear?

In [122]:
a.clear()

In [123]:
a

[]

**(copy)**

In [124]:
a=[1,2,3,4]
a.copy?

In [126]:
b=a.copy()
b

[1, 2, 3, 4]

**(count)**

In [129]:
a=[1,1,2,3,3,4,4,4,]
a.count(1)

2

In [130]:
a.count(2) #특정 원소가 몇개 포함되어있는지 숫자 세줌

1

**(extend)**

In [131]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [132]:
a.extend(b)
a

[1, 2, 3, 4, -1, -2, -3, -4]

In [133]:
a.append(b)   
a

[1, 2, 3, 4, -1, -2, -3, -4, [-1, -2, -3, -4]]

**(index)**

In [136]:
a=[11,22,'a',True,22]
a.index(True)

3

In [137]:
a.index('a')

2

In [139]:
a.index(22)

1

**(insert)**

In [149]:
a=[1,2,3]

In [151]:
a.insert(1,88)
a

[1, 88, 2, 3]

**(pop)**

In [152]:
a=['a',1,2,'d']
a.pop()   # index= -1이므로 마지막원소가 나타남

'd'

In [153]:
a   # a는 마지막 원소가 사라진 상태

['a', 1, 2]

In [154]:
a.pop(0)   # index=0 이므로 첫번째 원소가 나타남

'a'

In [155]:
a    # a에서는 첫번쨰 원소가 사라진 상태

[1, 2]

**(remove)**

In [161]:
a=['a',2,3,'d']
a.remove('d')

In [162]:
a

['a', 2, 3]

In [163]:
a.remove('a')
a

[2, 3]

**(reverse)**

In [164]:
a=[1,2,3,4]
a.reverse()
a

[4, 3, 2, 1]

**(sort)**

In [165]:
a=[1,3,2,4]
a.sort()
a

[1, 2, 3, 4]

(다른예제들)

In [166]:
a=list('boram')
a

['b', 'o', 'r', 'a', 'm']

In [167]:
a.sort()
a

['a', 'b', 'm', 'o', 'r']

In [168]:
a.sort(reverse=True)
a

['r', 'o', 'm', 'b', 'a']

## 중첩리스트

In [169]:
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

`-` A는 아래와 같은 매트릭스로 이해할 수 있다.

$
\bf{A}=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{bmatrix}
$

`-` A에서 (2,1)의 원소를 뽑고 싶다. =  1을 뽑고싶다. 

In [173]:
A[1,0]

TypeError: list indices must be integers or slices, not tuple

- 실패

In [174]:
A[1][0]

4

- 성공

성고의 이유를 분석해 보자.

In [175]:
A[0]

[1, 2, 3]

In [176]:
A[0][0]

1

`-` 매트릭스는 아니지만 매트릭스 같음!
- 1차원 배열을 다차원 배열로 확장할 수 있는 기본 아이디어를 제공함

## 리스트컴프리헨션 (★★★)

`-` 리스트 컴프리헨션을 이해하기 전에 for문에 대하여 알아보자.

[예비학습] `for`문 벼락치기

프로그램안에서 반복해서 무언가를 하고싶다 $\to$ for

In [177]:
for i in [0,1,2,3]:   # 반복실행계획
    print(i)          # 반복실행내용, 탭을 이용하여 들여쓰기 해야한다. 

0
1
2
3


(예제) 1,2,3,4의 합을 for문을 이용하여 구해보자.

In [179]:
_sum = 0
for i in [1,2,3,4]:
    _sum = _sum + i


In [180]:
_sum

10

`-` 예제: $ 2^0, 2^1, 2^2, 2^3$ 를 원소로 가지는 리스트를 생성

(풀이1)

In [182]:
x=[2**0, 2**1, 2**2, 2**3]    ## 2의 0승
x

[1, 2, 4, 8]

(풀이2) for문을 이용

In [183]:
x=[]
for i in [0,1,2,3]:
    x.append(2**i)  

In [184]:
x

[1, 2, 4, 8]

(풀이3) for문을 이용

In [185]:
x=[]
for i in [0,1,2,3]:
    x= x+[2**i]
x

[1, 2, 4, 8]

(풀이4) for문을 이용

In [187]:
x=[]
for i in [0,1,2,3]:
    x+= [2**i]
x(풀이2) for문을 이용

[1, 2, 4, 8]

(풀이5) 리스트컴프리헨션을 이용한 풀이

In [188]:
x= [2**i for i in [0,1,2,3]]
x

[1, 2, 4, 8]

`-` 리스트컴프리헨션의 문법 암기방법
- 집합에서 조건제시법을 연상
- 원소나열법, 조건제시법
- $\{2^0, 2^1, 2^2, 2^3\} = \{2^i: \text{for} i \in \{0,1,2,3\}$

`-` 리스트컴프리헨션이란?
- 리스트를 매우 효율적으로 만드는 테크닉
- for문에 비하여 가지고 있는 장점 : 1. 코드가 간결하다. 2, 빠르다

`-` 예제: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들자.

In [189]:
['SSSS','PPPP','AAAA','MMMM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

(풀이)


In [190]:
[i*4 for i in 'SPAM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

`-` 예제: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들자.

`-` 예제: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들자.

In [191]:
['X1','X2','X3','Y1','Y2','Y3']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

(풀이)



In [194]:
for i in 'XY':
    for j in '123':
        print(i+j)

X1
X2
X3
Y1
Y2
Y3


In [195]:
[i+j for i in 'XY' for j in '123']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

`-` 예제: 리스트 컴프리헨션을 이용하여 통계1,,..,통계5,수학1,...,수학5를 만들어라 

(풀이)

In [199]:
[i+j for i in ['stat', 'math'] for j in '12345']

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

(다른풀이) 참고로 for문을 쓰면 좀 복잡해진다.

In [201]:
_lst=[]
for x in ['stat', 'math']:
    for y in '12345':
        _lst = _lst + [x+y]

In [202]:
_lst

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

`-` 예제: 'jbnu'를 이용하여 아래와 같은 리스트르 만들어라.

In [205]:
['j','b','n','u']

['j', 'b', 'n', 'u']

In [206]:
list('jbnu')

['j', 'b', 'n', 'u']

(풀이)

In [207]:
[x for x in 'jbnu']

['j', 'b', 'n', 'u']

`-`예제: x에는 무엇이 있을까?

(경우1)

In [209]:
x=1
lst=[]
for x in 'jbnu':
    lst = lst + [x]

In [210]:
lst

['j', 'b', 'n', 'u']

In [211]:
x

'u'

(경우2)

In [212]:
x=1
lst = [x for x in 'jbnu']
lst

['j', 'b', 'n', 'u']

In [213]:
x

1

`-` 예제: [X1,X2,X3,...,X100]과 같은 리스트를 만들어보자.

(풀이)

In [220]:
['X'+str(i) for i in [1,2,3,4]]

['X1', 'X2', 'X3', 'X4']

In [223]:
['X'+str(i) for i in [1:100]]   #오류!!

SyntaxError: invalid syntax (1716365648.py, line 1)

[예비학습]

In [222]:
range(0,10)

range(0, 10)

In [224]:
_tmp = range(0,10)

In [225]:
type(_tmp)

range

In [226]:
list(_tmp)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [228]:
list(range(0,10)) #0을 포함, 10을 미포함

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 이게 중요한 것. range(0,10)을 리스트화시키면 [0,1,2,...,9]와 같은기능을 얻을 수 있다.

In [229]:
list(range(10))  # 0은 생략가능

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [230]:
list(range(2,10))  # 2는 포함, 10은 미포함

[2, 3, 4, 5, 6, 7, 8, 9]

In [231]:
list(range(1,10,2))  # 2칸씩! 

[1, 3, 5, 7, 9]

예비학습 끝

In [232]:
['X'+str(i) for i in list(range(1,101))]  # 세로로 넘 길엉 

['X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X7',
 'X8',
 'X9',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X25',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X72',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100']

(아래와 같은 풀이도 가능)

In [233]:
['X'+str(i) for i in range(1,13)]  # 리스트화해주지 않아도 가능 for i in 뒤에 list뿐 아니라.. str도 되고... 

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

(딴생각) for문 뒤에 올 수 있는 것이 무엇인지 생각해보자.

In [234]:
for i in '1234':
    print(i)

1
2
3
4


In [235]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [236]:
for i in (1,2,3,4):   # 튜플
    print(i)

1
2
3
4


In [237]:
for i in {1,2,3,4}: # set
    print(i)

1
2
3
4


In [238]:
for i in {'name':'iu','age':31}:   # 딕셔너리
    print(i)

name
age


In [240]:
for i in range(1,5):
    print(i)

1
2
3
4


(숙제)

리스트컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라


['X1','X2X2','X3X3X3','X4X4X4X4','X5X5X5X5X5']


In [246]:
[('X'+str(i))*i for i in range(1,6)]

['X1', 'X2X2', 'X3X3X3', 'X4X4X4X4', 'X5X5X5X5X5']