# imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import networkx as nx
import sklearn
import xgboost as xgb

# sklearn
from sklearn import model_selection # split함수이용
from sklearn import ensemble # RF,GBM
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler

# gnn
import torch
import torch.nn.functional as F
import torch_geometric
from torch_geometric.nn import GCNConv



# pyod
from pyod.models.knn import KNN
from pyod.utils.data import generate_data
from pyod.models.kde import KDE




/home/coco/anaconda3/envs/py38/lib/python3.8/site-packages/torch_geometric/typing.py:18: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /home/coco/anaconda3/envs/py38/lib/python3.8/site-packages/libpyg.so: undefined symbol: _ZN2at4_ops12split_Tensor4callERKNS_6TensorEN3c106SymIntEl
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/coco/anaconda3/envs/py38/lib/python3.8/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/coco/anaconda3/envs/py38/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/coco/anaconda3/envs/py38/lib/python3.8/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/coco/anaconda3/en

In [2]:
def down_sample_textbook(df):
    df_majority = df[df.is_fraud==0].copy()
    df_minority = df[df.is_fraud==1].copy()
    df_maj_dowsampled = sklearn.utils.resample(df_majority, n_samples=len(df_minority), replace=False, random_state=42)
    df_downsampled = pd.concat([df_minority, df_maj_dowsampled])
    return df_downsampled

def compute_time_difference(group):
    n = len(group)
    result = []
    for i in range(n):
        for j in range(n):
            time_difference = abs(group.iloc[i].trans_date_trans_time.value - group.iloc[j].trans_date_trans_time.value)
            result.append([group.iloc[i].name, group.iloc[j].name, time_difference])
    return result

def mask(df):
    df_tr,df_test = sklearn.model_selection.train_test_split(df, random_state=42)
    N = len(df)
    train_mask = [i in df_tr.index for i in range(N)]
    test_mask = [i in df_test.index for i in range(N)]
    train_mask = np.array(train_mask)
    test_mask = np.array(test_mask)
    return train_mask, test_mask

def edge_index_selected(edge_index):
    theta = edge_index[:,2].mean()
    edge_index[:,2] = (np.exp(-edge_index[:,2]/theta) != 1)*(np.exp(-edge_index[:,2]/theta))
    edge_index = edge_index.tolist()
    mean_ = np.array(edge_index)[:,2].mean()
    selected_edges = [(int(row[0]), int(row[1])) for row in edge_index if row[2] > mean_]
    edge_index_selected = torch.tensor(selected_edges, dtype=torch.long).t()
    return edge_index_selected

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(1, 16)
        self.conv2 = GCNConv(16,2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)
    
    
metrics = [sklearn.metrics.accuracy_score,
           sklearn.metrics.precision_score,
           sklearn.metrics.recall_score,
           sklearn.metrics.f1_score]

In [3]:
fraudTrain = pd.read_csv("~/Desktop/fraudTrain.csv").iloc[:,1:]

In [4]:
fraudTrain = fraudTrain.assign(trans_date_trans_time= list(map(lambda x: pd.to_datetime(x), fraudTrain.trans_date_trans_time)))
fraudTrain

trans_date_trans_time        cc_num  \
0         2019-01-01 00:00:00  2.703190e+15   
1         2019-01-01 00:00:00  6.304230e+11   
2         2019-01-01 00:00:00  3.885950e+13   
3         2019-01-01 00:01:00  3.534090e+15   
4         2019-01-01 00:03:00  3.755340e+14   
...                       ...           ...   
1048570   2020-03-10 16:07:00  6.011980e+15   
1048571   2020-03-10 16:07:00  4.839040e+15   
1048572   2020-03-10 16:08:00  5.718440e+11   
1048573   2020-03-10 16:08:00  4.646850e+18   
1048574   2020-03-10 16:08:00  2.283740e+15   

                                   merchant        category     amt  \
0                fraud_Rippin, Kub and Mann        misc_net    4.97   
1           fraud_Heller, Gutmann and Zieme     grocery_pos  107.23   
2                      fraud_Lind-Buckridge   entertainment  220.11   
3        fraud_Kutch, Hermiston and Farrell   gas_transport   45.00   
4                       fraud_Keeling-Crist        misc_pos   41.96   
...                                     ...             ...     ...   
1048570                     fraud_Fadel Inc  health_fitness   77.00   
1048571    fraud_Cremin, Hamill and Reichel        misc_pos  116.94   
1048572  fraud_O'Connell, Botsford and Hand            home   21.27   
1048573              fraud_Thompson-Gleason  health_fitness    9.52   
1048574                 fraud_Buckridge PLC        misc_pos    6.81   

             first      last gender                            street  \
0         Jennifer     Banks      F                    561 Perry Cove   
1        Stephanie      Gill      F      43039 Riley Greens Suite 393   
2           Edward   Sanchez      M          594 White Dale Suite 530   
3           Jeremy     White      M       9443 Cynthia Court Apt. 038   
4            Tyler    Garcia      M                  408 Bradley Rest   
...            ...       ...    ...                               ...   
1048570      Haley    Wagner      F            05561 Farrell Crescent   
1048571   Meredith  Campbell      F               043 Hanson Turnpike   
1048572      Susan     Mills      F                  005 Cody Estates   
1048573      Julia      Bell      F               576 House Crossroad   
1048574    Shannon  Williams      F  9345 Spencer Junctions Suite 183   

                   city  ...      lat      long  city_pop  \
0        Moravian Falls  ...  36.0788  -81.1781      3495   
1                Orient  ...  48.8878 -118.2105       149   
2            Malad City  ...  42.1808 -112.2620      4154   
3               Boulder  ...  46.2306 -112.1138      1939   
4              Doe Hill  ...  38.4207  -79.4629        99   
...                 ...  ...      ...       ...       ...   
1048570       Annapolis  ...  39.0305  -76.5515     92106   
1048571         Hedrick  ...  41.1826  -92.3097      1583   
1048572      Louisville  ...  38.2507  -85.7476    736284   
1048573   West Sayville  ...  40.7320  -73.1000      4056   
1048574      Alpharetta  ...  34.0770  -84.3033    165556   

                                       job         dob  \
0                Psychologist, counselling  1988-03-09   
1        Special educational needs teacher  1978-06-21   
2              Nature conservation officer  1962-01-19   
3                          Patent attorney  1967-01-12   
4           Dance movement psychotherapist  1986-03-28   
...                                    ...         ...   
1048570    Accountant, chartered certified  1943-05-28   
1048571                         Geochemist  1999-06-28   
1048572              Engineering geologist  1952-04-02   
1048573                  Film/video editor  1990-06-25   
1048574                     Prison officer  1997-12-27   

                                trans_num   unix_time  merch_lat  merch_long  \
0        0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1        1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2        a1a22d70485983eac12b5b88dad1cf95  

## 데이터정리

In [5]:
_df1 = fraudTrain[fraudTrain["is_fraud"] == 0].sample(frac=0.20, random_state=42)
_df2 = fraudTrain[fraudTrain["is_fraud"] == 1]
df02 = pd.concat([_df1,_df2])
df02.shape

(214520, 22)

In [6]:
df02 = df02.reset_index()

In [13]:
# df50 = down_sample_textbook(df02)
# df50 = df50.reset_index()
# df50.shape

------------------------------------------------------------------------

### tr/test

In [7]:
df02_tr,df02_test = sklearn.model_selection.train_test_split(df02, random_state=42)

In [8]:
train_mask, test_mask = mask(df02)

------------------------------------------------------------------------

### edge_index 설정

In [9]:
groups = df02.groupby("cc_num")

In [11]:
edge_index = np.load('edge_index_list_plus02.npy').astype(np.float64)
edge_index.shape

(65831594, 3)

In [12]:
edge_index

array([[2.881000e+03, 2.881000e+03, 0.000000e+00],
       [2.881000e+03, 3.061000e+03, 1.909224e+16],
       [2.881000e+03, 4.867000e+03, 2.427060e+15],
       ...,
       [2.127710e+05, 2.127650e+05, 2.688000e+13],
       [2.127710e+05, 2.127690e+05, 9.000000e+11],
       [2.127710e+05, 2.127710e+05, 0.000000e+00]])

In [13]:
edge_index_selected = edge_index_selected(edge_index)

In [14]:
edge_index_selected

tensor([[  2881,   2881,   2881,  ..., 212771, 212771, 212771],
        [  4867,   9618,  12525,  ..., 212759, 212765, 212769]])

---


### data설정(x, edge_index, y)

In [16]:
x = torch.tensor(df02['amt'], dtype=torch.float).reshape(-1,1)
y = torch.tensor(df02['is_fraud'],dtype=torch.int64)
data = torch_geometric.data.Data(x=x, edge_index = edge_index_selected, y=y, train_mask = train_mask, test_mask = test_mask)
data

Data(x=[214520, 1], edge_index=[2, 29970380], y=[214520], train_mask=[214520], test_mask=[214520])

---



## 분석 1(GCN)

In [19]:
torch.manual_seed(202250926)
X = (data.x[data.train_mask]).numpy()
XX = (data.x[data.test_mask]).numpy()
y = (data.y[data.train_mask]).numpy()
yy = (data.y[data.test_mask]).numpy()

model = GCN()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
model.train()
for epoch in range(400):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
model.eval()
pred = model(data).argmax(dim=1)
yyhat = pred[data.test_mask]

_results1= pd.DataFrame({m.__name__:[m(yy,yyhat).round(6)] for m in metrics},index=['분석1'])
_results1

accuracy_score  precision_score  recall_score  f1_score
분석1        0.973392         0.832558      0.114013   0.20056

---

## 분석2(pyod_KNN)

In [20]:
torch.manual_seed(202250926)
X = np.array(df02_tr.loc[:, ['amt']])
XX = np.array(df02_test.loc[:, ['amt']])
y = np.array(df02_tr.is_fraud)
yy = np.array(df02_test.is_fraud)
clf = KNN()
clf.fit(X)
yyhat = clf.predict(XX)
_results2= pd.DataFrame({m.__name__:[m(yy,yyhat).round(6)] for m in metrics},index=['분석2'])
_results2

accuracy_score  precision_score  recall_score  f1_score
분석2        0.920809         0.235527      0.759236  0.359523

---

## 분석3(pyod_KDE)

In [21]:
torch.manual_seed(202250926)
X = np.array(df02_tr.loc[:, ['amt']])
XX = np.array(df02_test.loc[:, ['amt']])
y = np.array(df02_tr.is_fraud)
yy = np.array(df02_test.is_fraud)
clf = KDE()
clf.fit(X)
yyhat = clf.predict(XX)
_results3= pd.DataFrame({m.__name__:[m(yy,yyhat).round(6)] for m in metrics},index=['분석3'])
_results3

accuracy_score  precision_score  recall_score  f1_score
분석3        0.915551         0.222992      0.758599  0.344668

In [22]:
yyhat

array([0, 0, 1, ..., 0, 0, 0])